#!/usr/bin/env python3
# Fetches trip info from the DB ICE API and prints it nicely.
# Idea mostly taken from: https://git.catgirl.cloud/999eagle/dotfiles-nix
import sys
from argparse import ArgumentParser
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Iterable

import requests
from multisn8 import fmt_datetime


ENDPOINT = "https://iceportal.de/api1/rs/"


def ms_timestamp(stamp: int | None) -> datetime | None:
    if stamp is None:
        return None
    return datetime.fromtimestamp(stamp / 1000)


@dataclass
class Stop:
    data: dict

    @property
    def name(self) -> str:
        return self.data["station"]["name"]

    @property
    def track(self) -> str:
        """Note that tracks aren't always numerical."""
        return self.data["track"]["actual"]

    # timestamps from the db api seem to be
    # always in microsecond precision
    # ...but they're always multiples of 1000 * 60
    # ...so the precision is in minutes anyway
    @property
    def arrival(self) -> datetime | None:
        return ms_timestamp(self.data["timetable"]["actualArrivalTime"])

    @property
    def departure(self) -> datetime | None:
        return ms_timestamp(self.data["timetable"]["actualDepartureTime"])

    def __str__(self) -> str:
        out = f"{self.name} #{self.track} "

        if self.arrival is None:
            sign = "<"
            time = self.departure
        else:
            sign = ">"
            time = self.arrival

        out += f"{sign}{fmt_datetime(time)}"
        return out


class Train:
    """Fetches and formats information about the current train nicely."""

    def __init__(self, endpoint=ENDPOINT):
        self.status = requests.get(endpoint + "status").json()
        self.trip = requests.get(endpoint + "tripInfo/trip").json()["trip"]

    @property
    def speed(self) -> int:
        """Speed in km/h."""
        return int(self.status["speed"])

    @property
    def train_type(self) -> str:
        return self.status["trainType"]

    @property
    def series(self) -> str:
        return self.status["series"]

    @property
    def traffic_id(self) -> str:
        """Traff"""
        return self.trip["vzn"]

    @property
    def stops(self) -> Iterable[Stop]:
        """All unvisited stops."""
        return map(
            Stop,
            (
                stop
                for stop in self.trip["stops"]
                if stop["info"]["positionStatus"] == "future"
            ),
        )

    def vehicle(self) -> str:
        """Textual description of the vehicle's state."""
        return " ".join([self.train_type, self.series, f"@{self.speed} km/h"])

    def final(self) -> str:
        """What the trip very coarsely does."""
        return f"{self.traffic_id} to {self.stops[-1]}"


def general():
    train = Train()
    print(
        train.vehicle(),
        train.final(),
        f"next: {next(train.stops)}",
        sep="\n",
    )


def all():
    train = Train()
    print(*train.stops, sep="\n")


def main():
    parser = ArgumentParser(description="chooo choooo", epilog="only works in ICEs")
    parser.set_defaults(func=general)

    sub = parser.add_subparsers()

    callbacks = {
        "general": general,
        "vehicle": lambda: print(Train().vehicle()),
        "final": lambda: print(Train().final()),
        "next": lambda: print(next(Train().stops)),
        "all": all,
    }

    for name, func in callbacks.items():
        cmd = sub.add_parser(name)
        cmd.set_defaults(func=func)

    parser.parse_args().func()


if __name__ == "__main__":
    main()
