#!/usr/bin/env zsh
set -euo pipefail

for machine in `cat "$state_share/connected-machines"`; do
	if not reachable "$machine"; then
		continue
	fi
	if [[ "$machine" == "$hostname" ]]; then
		"$@" || true
	else
		ssh "$machine" "$@" || true
	fi
done

