#!/usr/bin/env sh
set -euo pipefail
. util

machine=`hostname`
now=`date --rfc-3339=seconds`
name="${name:-small}"

export archive="$HOME/_archive/$now $machine-$name.tar.zst"

backup-create "$@"
backup-transfer-physical || true
backup-transfer-net || true

complete all backed up!
