#!/usr/bin/env zsh
set -euo pipefail
. util

target="traveled"

begin transferring to machine "$target"

if not ping -c1 -w1 "$target"; then
	error machine "$target" not reachable, aborting
fi

# TODO: encryption

part copying


