#!/usr/bin/env zsh
set -euo pipefail
. util

# default, then selective override
subjects=`echo $HOME/{notes,studio,media} "$core" "$state_share"`
subjects=${@:-$subjects}

maintenance

begin archiving to "$archive"
hint ' source size:' `adu $subjects`
tar --zstd --sort name --create --file "$archive" $subjects
hint 'archive size:' `adu "$archive"`

