#!/usr/bin/env zsh
# Transfers $archive to a hardcoded disk
set -euo pipefail
. util

permadisk="shots" # partition label

block="/dev/disk/by-label/$permadisk"
mount="/run/media/$(whoami)/$permadisk"
final="$mount/$(basename "$archive")"

if [[ ! -e "$block" ]]; then
	error disk "$permadisk" is not plugged in, not transferring there
	exit 1
fi

begin transferring to disk "$permadisk"

if mountpoint -q "$mount"; then
	warn "$permadisk" already mounted
else
	part mounting "$permadisk"
	udisksctl mount -b "$block"
fi

part copying archive over
pv "$archive" > "$final"

part flushing filesystem caches
sync "$final"

part unmounting disk
udisksctl unmount -b "$block"

complete transfer finished!

