#!/usr/bin/env -S zsh -i
# interactive mode is to get $PROMPT and $RPROMPT visible
set -euo pipefail

case "$1" in
	# TODO: add adb case:
	#
	# + install termux
	# + in termux, install openssh, configure sshd
	# + on this machine, generate ~/.ssh/id_to_termux ssh key
	# + send the public ssh key to termux
	# + launch sshd on termux (maybe even sv-enable sshd)
	#
	# then spill over into the termux case via ;&
	(termux) 
		to "$1" <<REMOTE
			pkg install --yes python git git-lfs zsh fd ripgrep magic-wormhole-rs direnv difftastic termux-services neovim
			chsh -s zsh
REMOTE
	;;
esac

to "$1" <<REMOTE
	set -euo pipefail
	cd ~
	mkdir -p zero/core
	cd zero

	git clone https://github.com/MultisampledNight/core.git || true
	cd core
	git pull || true

	python3 ./bootstrap/distribute_symlinks.py --only-user --verbose

	echo "PROMPT='$PROMPT'" > ~/.privaterc
	echo "RPROMPT='$RPROMPT'" >> ~/.privaterc
REMOTE

