#!/usr/bin/env zsh
set -euo pipefail
handle="$1"

. adblib

alias jq='jq -r'

function line() {
	echo "$details" | head -n "$1" | tail -n1
}
function batfmt() {
	echo "$battery" | jq ". | \"$1\""
}

props=`echo '
	ro.{
		board.platform,
		hardware,
		soc.{
			manufacturer,
			model
		},
		build.version.{
			release,
			sdk,
			min_supported_target_sdk,
			security_patch
		},
		product.{
			cpu.abi,
			vendor.{
				manufacturer,
				model
			}
		},
		system.build.date.utc,
		serialno
	}
' | tr -d '[:space:]'`

details=`sh "
	for name in $props; do
		getprop \"\\$name\"
	done

	cat /proc/uptime

	cat /sys/bus/cpu/devices/cpu0/cpufreq/cpuinfo_{min,max}_freq
	nproc
	dumpsys cpuinfo | head -n1

	dumpsys battery
"`

platform=`line 1`
hardware=`line 2`
soc_manufacturer=`line 3`
soc=`line 4`
os_release=`line 5`
sdk=`line 6`
min_sdk=`line 7`
security_patch=`line 8`
abi=`line 9`
manufacturer=`line 10`
model=`line 11`
os_built_at="$(date --rfc-3339=seconds --date=@`line 12` --utc)"
serialno=`line 13`

uptime=`line 14`

freq_min=`line 15`
freq_max=`line 16`
nproc=`line 17`
cpuload=`line 18`

battery=`echo "$details" | tail -n+19 | yq '.[]'`

begin "$manufacturer $model" `fade "$hardware"`

part SOC \
	"$platform" "$soc" \
	`fade "$soc_manufacturer"`

part CPU \
	`echo "$cpuload" | rg 'Load: (\S*) / (\S*) / (\S*)' -r '$1, $2, $3'` \
	$(fade \
		"$nproc"core \
		`echo "[$freq_min, $freq_max]" | jq 'map(. / 1000) | "[\(.[0]):\(.[1])]GHz"'` \
		"$abi")

part BAT \
	`batfmt '\(
		.level
	)% \(
		if to_entries | map(select(.key | contains("powered"))) | any(.value)
		then "↑"
		else "↓"
		end
	)'` \
	\
	$(fade `batfmt '\(
		.voltage / 1000
	)V \(
		."Charge counter" / 1000
	)mAh \(
		.temperature / 10
	)°C \(
		.technology | ascii_downcase
	)'`)

# stored in seconds, first part is uptime (second part is just idle time)
part UPT \
	`echo "$uptime" | cut -f1 -d' ' | jq '
		(. / 60 % 60) as \$m
		| (. / 60 / 60 % 24) as \$h
		| (. / 60 / 60 / 24) as \$d
		| "\($d | floor)d \($h | floor)h \($m | round)min"
	'`


part OSY \
	"Android $os_release" \
	`fade \
		sdk"$min_sdk":"$sdk" \
		sec"$security_patch" \
		built"$os_built_at"`

if [[ ! -z "${serial:-}" ]]; then
	part SER \
		"$serialno"
fi

