#!/usr/bin/env zsh
set -euo pipefail
handle="$1"

. adblib

releases='https://archive.mozilla.org/pub/fenix/releases'
abi=`device-abi "$handle"`

# slash is important: otherwise the webserver appears to think it's a file and 404s
version=`curlj "$releases/" \
	| jq '.prefixes | map(rtrimstr("/"))' \
	| version-filter-stable \
	| version-newest \
	| jq -r`

export url="$releases/$version/android\
/fenix-$version-android-$abi\
/fenix-$version.multi.android-$abi.apk"
export package='org.mozilla.firefox'

device-update-apk "$handle"

