#!/usr/bin/env zsh
set -xeuo pipefail

args=()

if [[ ${#@} -gt 2 ]]; then
	args+=(--format "$1")
	shift
fi

if [[ -e "$2" ]]; then
	echo "$2 already exists; skipping"
fi

yt-dlp $args -t sleep --output "unproc.$2" "$1"
recode-video "unproc.$2" "$2"
rm "unproc.$2"
