#!/usr/bin/env zsh
# get-last-image -- downloads the last camera image from the connected ADB device
set -euo pipefail

images='/sdcard/DCIM/Camera'
last=`adb shell ls -1c "$images" '|' head -n1`

adb pull "$images/$last" >/dev/null
echo "$last"
