#!/usr/bin/env zsh
# doesn't take any arguments: expects env variables $url and $package to be set
set -euo pipefail

. util

apk="$package.apk"

mkcd "$apk_stash"
rm -f "$apk"
curlc -Lo "$apk" "$url"

