#!/usr/bin/env sh
# recode-video -- arguments are source target, re-encodes to av1 with opus
set -eu

# use libsvtav1: really damn fast and good configurability
# https://trac.ffmpeg.org/wiki/Encode/AV1#SVT-AV1
# bias towards speed and faster decoding

ffmpeg \
	-hwaccel auto \
	-i "$1" \
	-f webm \
	-vcodec libsvtav1 \
	-acodec libopus \
	-preset 7 \
	-svtav1-params fast-decode=2 \
	"$2"
