#!/usr/bin/env zsh
# recode-video [source] [target] -- re-encodes to av1 with opus
set -eu

# use libsvtav1: really damn fast and good configurability
# bias towards speed and faster decoding
#
# https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Parameters.md
# https://trac.ffmpeg.org/wiki/Encode/AV1#SVT-AV1

# have to be colon-separated (required by ffmpeg's libsvtav1 integration)
# but on one line would be too long, so i'm doing this
svtav1_params=(
	# better to decode faster
	fast-decode=2
	# want to improve low-contrast cases
	enable-variance-boost=1
	variance-boost-strength=3
)

ffmpeg \
	-hwaccel auto \
	-i "$1" \
	-f webm \
	-vcodec libsvtav1 \
		-preset 5 \
		-svtav1-params "${(j/:/)svtav1_params}" \
	-acodec libopus \
	"$2"
