#!/usr/bin/env zsh
# rsync with a few common args
set -euo pipefail

rsync \
	--delete \
	--update \
	--recursive \
	--itemize-changes \
	--human-readable \
	--compress \
	--partial \
	--times \
	--atimes \
	--open-noatime \
	--perms \
	--xattrs \
	--stats \
	"$@"
