#!/usr/bin/env zsh
# ssh-wl-remote-screen [target] -- uses [target] as 
set -euo pipefail

# based on
# https://superuser.com/questions/1434779/using-a-tablet-as-a-second-monitor-with-wayland#1652951
# https://www.reddit.com/r/swaywm/comments/k1zl41/thank_you_devs_free_ipad_repurposed_as_a_second/

target="$1"
output='HEADLESS-1'
port='8001'

if ! swaymsg -t get_outputs |
	jqc "map(.name) | contains([\"$output\"])";
then
	# in the source code, argv to the command is not used
	swaymsg create_output
fi

# local side; vnc server
wayvnc \
	--output="$output" \
	--max-fps=60 \
	--gpu \
	::1 \
	"$port" \
	&

# remote side; vnc client (tunneled via SSH)
ssh \
	-R "[::1]:$port" \
	"$target" \
	<<REMOTE
WAYLAND_DISPLAY=wayland-1 remmina \
	-k -c \
	"vnc://[::1]:$port" \
REMOTE

pkill wayvnc

