#!/usr/bin/env zsh
set -euo pipefail
. util

if [[ ${#@} -lt 1 ]]; then
	error "usage: <machine> [<command-and-args...>]"
	return 1
fi

target="$1"

# android-specific stuff
specify=()
# zsh-specific syntax: $+ echoes 1 if var is set and 0 otherwise
if (( $+handle )); then
	specify=(-s "$handle")
fi

case "$target" in
	(adb)
		adb $specify wait-for-device
		connector=(adb $specify shell)
	;;
	(termux)
		adb $specify forward tcp:8022 tcp:8022
		connector=(ssh termux)
	;;
	(*)
		connector=(ssh "$target")
		if ssh "$target" waypipe --version >/dev/null; then
			connector=(
				wp
				--title-prefix "@$target "
				--threads `ssh "$target" nproc --ignore=1`
				$connector
			)
		fi
	;;
esac

shift 1
$connector "$@"

